### ISSUE TITLE
KeyError: 'fastapi_aad_auth\\ui\\login.html' when trying to run tests/testapp/server.py with .env

### ISSUE THREAD

**Issue by varun5001** [djpugh/fastapi_aad_auth#1]
@djpugh  I have cloned master branch and ran setup.py install, then i am trying to run tests/testapp/server.py with .env that has AAD_CLIENT_ID,AAD_TENANT_ID and AAD_CLIENT_SECRET

(my-env) PS C:\Users\user1\Downloads\fastapi_aad_auth-master\fastapi_aad_auth-master> uvicorn --host=0.0.0.0 tests.testapp.server:app --reload
?[32mINFO?[0m:     Uvicorn running on ?[1mhttp://0.0.0.0:8000?[0m (Press CTRL+C to quit)
?[32mINFO?[0m:     Started reloader process [?[36m?[1m24616?[0m] using ?[36m?[1mstatreload?[0m
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\user1\Anaconda\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\user1\Anaconda\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\user1\Anaconda\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\uvicorn\main.py", line 397, in serve
    config.load()
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\uvicorn\config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\user1\Anaconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\tests\testapp\server.py", line 11, in <module>
    from fastapi_aad_auth import AADAuth, AuthenticationState, Config
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\fastapi_aad_auth-0.0.1-py3.6.egg\fastapi_aad_auth\__init__.py", line 1, in <module>
    from fastapi_aad_auth.auth import AADAuth  # noqa F401
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\fastapi_aad_auth-0.0.1-py3.6.egg\fastapi_aad_auth\auth.py", line 14, in <module>
    from fastapi_aad_auth.config import Config
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\fastapi_aad_auth-0.0.1-py3.6.egg\fastapi_aad_auth\config.py", line 36, in <module>
    class LoginUIConfig(BaseSettings):
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\fastapi_aad_auth-0.0.1-py3.6.egg\fastapi_aad_auth\config.py", line 38, in LoginUIConfig
    template_file: FilePath = Field(resource_filename('fastapi_aad_auth.ui', 'login.html'), env='FASTAPI_AUTH_LOGIN_TEMPLATE_FILE')
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\pkg_resources\__init__.py", line 1143, in resource_filename
    self, resource_name
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\pkg_resources\__init__.py", line 1650, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "C:\Users\user1\downloads\fastapi_aad_auth-master\fastapi_aad_auth-master\my-env\lib\site-packages\pkg_resources\__init__.py", line 1671, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'fastapi_aad_auth\\ui\\login.html'

It will be also great help if you can share any articles that you published for using this package

**Comment by djpugh** [comment]
Hmm, apologies -I'm still working on this at the moment - its a bit of a passion project, so I work on it when I can, but I probably haven't got the sdist build correct - I will work on some docs for this too!

**Comment by djpugh** [comment]
I've worked on this some more, the linked PR (and then release) *should* close this.
